
module.exports = [
    {short:"  " , name:"Please select a county"},
    {short:"1" , name:"Mombasa"},
    {short:"2" , name:"Kwale"},
    {short:"3" , name:"Kilifi"},
    {short:"4" , name:"Tana River"},
    {short:"5" , name:"Lamu"},
    {short:"6" , name:"Taita-Taveta"},
    {short:"7" , name:"Garissa"},
    {short:"8" , name:"Wajir"},
    {short:"9" , name:"Mandera"},
    {short:"10" , name:"Marsabit"},
    {short:"11" , name:"Isiolo"},
    {short:"12" , name:"Meru"},
    {short:"13" , name:"Tharaka-Nithi"},
    {short:"14" , name:"Embu"},
    {short:"15" , name:"kitui"},
    {short:"16" , name:"Machakos"},
    {short:"17" , name:"Makueni"},
    {short:"18" , name:"Nyandarua"},
    {short:"19" , name:"Nyeri"},
    {short:"20" , name:"Kirinyaga"},
    {short:"21" , name:"Muranga"},
    {short:"22" , name:"KIambu"},
    {short:"23" , name:"Turkana"},
    {short:"24" , name:"West Pokot"},
    {short:"25" , name:"Samburu"},
    {short:"26" , name:"Trans-Nzoia"},
    {short:"27" , name:"Uasin Gishu"},
    {short:"28" , name:"Elgeyo-Marakwet"},
    {short:"29" , name:"Nandi"},
    {short:"30" , name:"Baringo"},
    {short:"31" , name:"Laikipia"},
    {short:"32" , name:"Nakuru"},
    {short:"33" , name:"Naroki"},
    {short:"34" , name:"Kajiado"},
    {short:"35" , name:"Kericho"},
    {short:"36" , name:"Bomet"},
    {short:"37" , name:"Kakamega"},
    {short:"38" , name:"Vihiga"},
    {short:"39" , name:"Bungoma"},
    {short:"40" , name:"Busia"},
    {short:"41" , name:"Siaya"},
    {short:"42" , name:"Kisumu"},
    {short:"43" , name:"Homa Bay"},
    {short:"44" , name:"Migori"},
    {short:"45" , name:"Kisii"},
    {short:"46" , name:"Nyamira"},
    {short:"47" , name:"Nairobi"},
    
];